name = "NMRInversions"
uuid = "55c20db2-0166-4687-95c3-62a9c7afb29b"
authors = ["Aristarchos Mavridis <aris.mav@hotmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
